// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SmartCartBackend.Infrastructure;

#nullable disable

namespace SmartCartBackend.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260125191655_123")]
    partial class _123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.ActivityLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("ActivityLevels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalName = "sedentary",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Сидячий образ жизни"
                        },
                        new
                        {
                            Id = 2,
                            InternalName = "lightly_active",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "1-3 тренировки"
                        },
                        new
                        {
                            Id = 3,
                            InternalName = "moderately_active",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "4-5 тренировок"
                        },
                        new
                        {
                            Id = 4,
                            InternalName = "very_active",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "6-7 тренировок"
                        },
                        new
                        {
                            Id = 5,
                            InternalName = "professional_active",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Профессиональный спорт"
                        });
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("Allergies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalName = "peanut",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Арахис"
                        },
                        new
                        {
                            Id = 2,
                            InternalName = "milk",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Молочное"
                        },
                        new
                        {
                            Id = 3,
                            InternalName = "eggs",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Яйца"
                        },
                        new
                        {
                            Id = 4,
                            InternalName = "gluten",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Глютен"
                        });
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.CookingTime", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("Limit")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("CookingTime", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalName = "small",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "До 15 мин"
                        },
                        new
                        {
                            Id = 2,
                            InternalName = "medium",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "15-30 мин"
                        },
                        new
                        {
                            Id = 3,
                            InternalName = "hard",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "30-60 мин"
                        },
                        new
                        {
                            Id = 4,
                            InternalName = "unlimited",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Не ограничено"
                        });
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.DietStrategy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("DietStrategies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Сохранить текущий вес и тонус",
                            InternalName = "form_maintenance",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Поддержание формы"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Увеличение мышечной массы и силы",
                            InternalName = "muscle_gain",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Набор массы"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Вкусные и разные блюда каждый день",
                            InternalName = "varied_diet",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Просто разнообразить питание"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Постепенное и комфортное похудение",
                            InternalName = "weight_loss",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Снижение веса"
                        });
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("Difficulty", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalName = "easy",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Легко"
                        },
                        new
                        {
                            Id = 2,
                            InternalName = "normal",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Средне"
                        },
                        new
                        {
                            Id = 3,
                            InternalName = "hard",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Сложно"
                        });
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MealTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Portions")
                        .HasColumnType("integer");

                    b.Property<string>("Recipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.HasIndex("MealTypeId");

                    b.ToTable("Dishes", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.DishCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("DishCategories", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.DishEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Dimensions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(384);

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TextVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DishId")
                        .IsUnique();

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Model");

                    b.HasIndex("Model", "TextVersion");

                    b.ToTable("DishEmbeddings", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.DishIngredient", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitId");

                    b.HasIndex("DishId", "IngredientId")
                        .IsUnique();

                    b.ToTable("DishIngredients", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.DishTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("DishId", "TagId")
                        .IsUnique();

                    b.ToTable("DishTags", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.FoodRation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InternalName")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodRation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalName = "three_main",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "3 основных"
                        },
                        new
                        {
                            Id = 2,
                            InternalName = "three_main_and_one_snack",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "3 основных + 1 перекус"
                        },
                        new
                        {
                            Id = 3,
                            InternalName = "three_main_and_two_snack",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "3 основных + 2 перекуса"
                        },
                        new
                        {
                            Id = 4,
                            InternalName = "interval_fasting",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "2 раза в день (интервальное голодание)"
                        });
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Calories")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("numeric");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal>("Fats")
                        .HasColumnType("numeric");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Proteins")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.IngredientAllergy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("AllergyId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.HasIndex("IngredientId", "AllergyId")
                        .IsUnique();

                    b.ToTable("IngredientAllergies", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.IngredientCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("IngredientCategories", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.MealType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("MealTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalName = "breakfast",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Завтрак"
                        },
                        new
                        {
                            Id = 2,
                            InternalName = "lunch",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Обед"
                        },
                        new
                        {
                            Id = 3,
                            InternalName = "snack",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Перекус"
                        },
                        new
                        {
                            Id = 4,
                            InternalName = "dinner",
                            IsAdded = false,
                            IsDeleted = false,
                            Title = "Ужин"
                        });
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.NutritionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionPlans", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.NutritionPlanChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Choice")
                        .HasColumnType("boolean");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("MealTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("PlanId");

                    b.ToTable("NutritionPlanChoices", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.NutritionPlanDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionPlanDrafts", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.PhoneVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Phone");

                    b.ToTable("PhoneVerifications", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Phone");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("InternalName")
                        .IsUnique();

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalName = "gram",
                            IsAdded = false,
                            IsDeleted = false,
                            ShortTitle = "г.",
                            Title = "Грамм"
                        },
                        new
                        {
                            Id = 2,
                            InternalName = "kilogram",
                            IsAdded = false,
                            IsDeleted = false,
                            ShortTitle = "кг.",
                            Title = "Килограмм"
                        },
                        new
                        {
                            Id = 3,
                            InternalName = "piece",
                            IsAdded = false,
                            IsDeleted = false,
                            ShortTitle = "шт.",
                            Title = "Штук"
                        },
                        new
                        {
                            Id = 4,
                            InternalName = "milliliter",
                            IsAdded = false,
                            IsDeleted = false,
                            ShortTitle = "мл.",
                            Title = "Миллилитр"
                        },
                        new
                        {
                            Id = 5,
                            InternalName = "liter",
                            IsAdded = false,
                            IsDeleted = false,
                            ShortTitle = "л.",
                            Title = "Литр"
                        },
                        new
                        {
                            Id = 6,
                            InternalName = "tablespoon",
                            IsAdded = false,
                            IsDeleted = false,
                            ShortTitle = "ст. л.",
                            Title = "Столовая ложка"
                        },
                        new
                        {
                            Id = 7,
                            InternalName = "teaspoon",
                            IsAdded = false,
                            IsDeleted = false,
                            ShortTitle = "ч. л.",
                            Title = "Чайная ложка"
                        },
                        new
                        {
                            Id = 8,
                            InternalName = "slice",
                            IsAdded = false,
                            IsDeleted = false,
                            ShortTitle = "ломтика",
                            Title = "Ломтик"
                        });
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExcludedProducts")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Height")
                        .HasPrecision(10, 1)
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasPrecision(10, 1)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLevelId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.UserAiRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorText")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RequestedAt");

                    b.HasIndex("UserId", "RequestedAt");

                    b.HasIndex("Provider", "Model", "RequestedAt");

                    b.ToTable("UserAiRequests", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.UserAllergy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AllergyId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAllergies", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Dish", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.DishCategory", "DishCategory")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("DishCategory");

                    b.Navigation("MealType");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.DishEmbedding", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.Dish", null)
                        .WithOne("DishEmbedding")
                        .HasForeignKey("SmartCardBackend.Domain.Entities.DishEmbedding", "DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.DishIngredient", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.DishTag", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.Dish", "Dish")
                        .WithMany("DishTags")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.Tag", "Tag")
                        .WithMany("DishTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.IngredientCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.IngredientAllergy", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.Allergy", "Allergy")
                        .WithMany("IngredientAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientAllergies")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.NutritionPlan", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.NutritionPlanDraft", "Draft")
                        .WithMany()
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.NutritionPlanChoice", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.NutritionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("MealType");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.NutritionPlanDraft", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.User", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.ActivityLevel", "ActivityLevel")
                        .WithMany()
                        .HasForeignKey("ActivityLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityLevel");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.UserAiRequest", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.UserAllergy", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.User", "User")
                        .WithMany("Allergies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("SmartCardBackend.Domain.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCardBackend.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Allergy", b =>
                {
                    b.Navigation("IngredientAllergies");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Dish", b =>
                {
                    b.Navigation("DishEmbedding");

                    b.Navigation("DishIngredients");

                    b.Navigation("DishTags");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.DishCategory", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("DishIngredients");

                    b.Navigation("IngredientAllergies");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.Tag", b =>
                {
                    b.Navigation("DishTags");
                });

            modelBuilder.Entity("SmartCardBackend.Domain.Entities.User", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
